
// Additional plants for variety
export const additionalPlants = [
  { name: 'Quinoa', scientific: 'Chenopodium quinoa' },
  { name: 'Amaranth', scientific: 'Amaranthus' },
  { name: 'Arugula', scientific: 'Eruca vesicaria' },
  { name: 'Bok Choy', scientific: 'Brassica rapa subsp. chinensis' },
  { name: 'Luffa', scientific: 'Luffa aegyptiaca' },
  { name: 'Sunchoke', scientific: 'Helianthus tuberosus' },
  { name: 'Okra', scientific: 'Abelmoschus esculentus' },
  { name: 'Jicama', scientific: 'Pachyrhizus erosus' },
  { name: 'Tomatillo', scientific: 'Physalis philadelphica' },
  { name: 'Kohlrabi', scientific: 'Brassica oleracea var. gongylodes' },
  { name: 'Celeriac', scientific: 'Apium graveolens var. rapaceum' },
  { name: 'Mizuna', scientific: 'Brassica rapa var. japonica' },
  { name: 'Rutabaga', scientific: 'Brassica napus var. napobrassica' },
  { name: 'Fava Bean', scientific: 'Vicia faba' },
  { name: 'Lentil', scientific: 'Lens culinaris' },
  { name: 'Chickpea', scientific: 'Cicer arietinum' },
  { name: 'Turnip', scientific: 'Brassica rapa subsp. rapa' },
  { name: 'Daikon Radish', scientific: 'Raphanus sativus var. longipinnatus' },
  { name: 'Salsify', scientific: 'Tragopogon porrifolius' },
  { name: 'Burdock', scientific: 'Arctium lappa' },
  { name: 'Watercress', scientific: 'Nasturtium officinale' },
  { name: 'Radicchio', scientific: 'Cichorium intybus var. foliosum' },
  { name: 'Endive', scientific: 'Cichorium endivia' },
  { name: 'Sorrel', scientific: 'Rumex acetosa' },
  { name: 'Shiso', scientific: 'Perilla frutescens' },
  { name: 'Lovage', scientific: 'Levisticum officinale' },
  { name: 'Horseradish', scientific: 'Armoracia rusticana' },
  { name: 'Stevia', scientific: 'Stevia rebaudiana' },
  { name: 'Comfrey', scientific: 'Symphytum officinale' },
  { name: 'Elecampane', scientific: 'Inula helenium' },
];
