
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmcjplcgoqdmpbtqbghz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtY2pwbGNnb3FkbXBidHFiZ2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDg0MDgsImV4cCI6MjA1OTg4NDQwOH0.farvq3EBNELF2mdIf_aZrZeBw99clQQJ-fFttB5bAO0";

// Get the current URL from the browser
const getBaseUrl = () => {
  if (typeof window !== 'undefined') {
    // Get the site URL from the browser
    const protocol = window.location.protocol;
    const host = window.location.host;
    return `${protocol}//${host}`;
  }
  return 'http://localhost:3000'; // Default fallback for server-side
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Use the redirectUrl property inside the auth options configuration
    storage: localStorage
  }
});
